------------------------------
-- Sequence Id From table person
------------------------------

--Permisos GRANT CREATE SEQUENCE TO NombreEsquema; al system

CREATE SEQUENCE sequencePersonId
 START WITH     1
 INCREMENT BY   1
 MINVALUE 0
 MAXVALUE 10000000
 NOCACHE
 NOCYCLE;

CREATE SEQUENCE sequenceBirdId
 START WITH     1
 INCREMENT BY   1
 MINVALUE 0
 MAXVALUE 10000000
 NOCACHE
 NOCYCLE;

 CREATE SEQUENCE sequenceDistrictId
 START WITH     1
 INCREMENT BY   1
 MINVALUE 0
 MAXVALUE 10000000
 NOCACHE
 NOCYCLE;

 CREATE SEQUENCE sequenceCityId
 START WITH     1
 INCREMENT BY   1
 MINVALUE 0
 MAXVALUE 10000000
 NOCACHE
 NOCYCLE;




 CREATE SEQUENCE sequenceProvinceId
 START WITH     1
 INCREMENT BY   1
 MINVALUE 0
 MAXVALUE 10000000
 NOCACHE
 NOCYCLE;

 CREATE SEQUENCE sequenceCountryId
 START WITH     1
 INCREMENT BY   1
 MINVALUE 0
 MAXVALUE 10000000
 NOCACHE
 NOCYCLE;

 CREATE SEQUENCE sequenceSpecieId
 START WITH     1
 INCREMENT BY   1
 MINVALUE 0
 MAXVALUE 10000000
 NOCACHE
 NOCYCLE;


 CREATE SEQUENCE sequenceGenderId
 START WITH     1
 INCREMENT BY   1
 MINVALUE 0
 MAXVALUE 10000000
 NOCACHE
 NOCYCLE;

 CREATE SEQUENCE sequenceFamilyId
 START WITH     1
 INCREMENT BY   1
 MINVALUE 0
 MAXVALUE 10000000
 NOCACHE
 NOCYCLE;

 CREATE SEQUENCE sequenceSuborderId
 START WITH     1
 INCREMENT BY   1
 MINVALUE 0
 MAXVALUE 10000000
 NOCACHE
 NOCYCLE;

 CREATE SEQUENCE sequenceOrderId
 START WITH     1
 INCREMENT BY   1
 MINVALUE 0
 MAXVALUE 10000000
 NOCACHE
 NOCYCLE;